jedentist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', views.homepage, name='index-app'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sudentis/', include('sudentis.urls')),
]

urlpatterns += staticfiles_urlpatterns()

sudentis/urls.py
from django.urls import path
from .views import index, DentistCreate, DentistDetailView, ClinicCreate, ClinicDetailView, HistoryUpdate, HistoryDetailView, dentist_add_work, attention_add, PatientUpdate, patient_add, PatientDetailView

app_name = 'sudentis'

urlpatterns = [
    path('', index, name='index'), # ex: /sudentis/
    path('dentist-create/', DentistCreate.as_view(), name='dentist-create'),
    path('dentist/<int:pk>/', DentistDetailView, name='dentist-detail'),
    path('clinic-create/', ClinicCreate.as_view(), name='clinic-create'),
    path('clinic/<int:pk>/', ClinicDetailView, name='clinic-detail'),
    path('clinic/<int:pk>/dentist-add/', dentist_add_work, name='dentist-add'),
    path('clinic/<int:pk>/patient-add/', patient_add, name='patient-add'),
    path('history-update/<int:pk>/', HistoryUpdate.as_view(), name='history-update'),
    path('history/<int:pk>/', HistoryDetailView, name='history-detail'),
    path('history/<int:pk>/attention-add/', attention_add, name='attention-add'),
    path('patient-update/<int:pk>/', PatientUpdate.as_view(), name='patient-update'),
    path('patient/<int:pk>/', PatientDetailView.as_view(), name='patient-detail')
]

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Sudentis 2.0</title>
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
	<div class="container-fluid" id="wrapper">
		<div class="row">
			<nav class="sidebar col-xs-12 col-sm-4 col-lg-3 col-xl-2">
				<h1 class="site-title"><a href="{% url 'index-app' %}"><em class="fa fa-rocket"></em> SuDentis</a></h1>				
				<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><em class="fa fa-bars"></em></a>
				<ul class="nav nav-pills flex-column sidebar-nav">
					{% block navpills %}{% endblock %}
				</ul>
				{% if user.is_authenticated %}
					<a href="{% url 'logout' %}" class="logout-button"><em class="fa fa-power-off"></em> Salir</a></nav>
				{% endif %}
			</nav>
			<main class="col-xs-12 col-sm-8 col-lg-9 col-xl-10 pt-3 pl-4 ml-auto">
				<header class="page-header row justify-center">
					<div class="col-md-6 col-lg-8" >
						{% block header %}<h1 class="float-left text-center text-md-left">Sudentis App para Dentistas y Provedores</h1>{% endblock %}
					</div>
					<div class="dropdown user-dropdown col-md-6 col-lg-4 text-center text-md-right">						
						{% if user.is_authenticated %}
						<div class="username mt-1">
							<h4 class="mb-1">{{ user.first_name }}</h4>
							<h6 class="text-muted">{{ user.username }}</h6>
							<h6 class="text-muted">{{ user.dentist.dentist_dni }}</h6>
						</div>
						<div class="username mt-1">
							<a class="dropdown-item" href="#"><em class="fa fa-user-circle mr-1"></em> Ver y Editar Perfil</a>
							<a class="dropdown-item" href="#"><em class="fa fa-sliders mr-1"></em> Preferences</a>
							<a class="dropdown-item" href="{% url 'logout' %}"><em class="fa fa-power-off mr-1"></em> Cerrar Sesion</a>
						</div>
						{% else %}
						<a href="{% url 'login' %}" role="button" class="btn btn-sm btn-primary font-weight-bold">Iniciar Sesion</a>
						{% endif %}
					</div>
					<div class="clear"></div>
				</header>
				<section class="row">
					<div class="col-sm-12">
						<section class="row">
							<div class="col-md-12 col-lg-8">
								{% block content %}{% endblock %}
							</div>
							<div class="col-md-12 col-lg-4">
								{% block helpers %}
								<div class="card mb-4">
									<div class="card-block">
										<h3 class="card-title">Calendario</h3>
										<h6 class="card-subtitle mb-2 text-muted">Ver dias libres y de atencion</h6>
										<!--
										<div class="user-progress justify-center">
											<div class="col-sm-3 col-md-2" style="padding: 0;">
												<img src="images/profile-pic.jpg" alt="profile photo" class="circle profile-photo" style="width: 100%; max-width: 100px;">
											</div>
											<div class="col-sm-9 col-md-10">
												<h6 class="pt-1">Username 1</h6>
												<div class="progress progress-custom">
													<div class="progress-bar bg-primary" style="width: 75%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
										</div>
										<div class="user-progress justify-center">
											<div class="col-sm-3 col-md-2" style="padding: 0;">
												<img src="images/profile-pic.jpg" alt="profile photo" class="circle profile-photo" style="width: 100%; max-width: 100px;">
											</div>
											<div class="col-sm-9 col-md-10">
												<h6 class="pt-1">Username 2</h6>
												<div class="progress progress-custom">
													<div class="progress-bar bg-primary" style="width: 50%" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
										</div>
										<div class="user-progress justify-center">
											<div class="col-sm-3 col-md-2" style="padding: 0;">
												<img src="images/profile-pic.jpg" alt="profile photo" class="circle profile-photo" style="width: 100%; max-width: 100px;">
											</div>
											<div class="col-sm-9 col-md-10">
												<h6 class="pt-1">Username 3</h6>
												<div class="progress progress-custom">
													<div class="progress-bar bg-primary" style="width: 25%" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
												</div>
											</div>
										</div>
										<div class="divider"></div>
										-->
										<div id="calendar"></div>
										<div class="divider"></div>
										<h3 class="card-title">Pendientes</h3>
										<h6 class="card-subtitle mb-2 text-muted">Notas importantes para el consultorio</h6>
										<ul class="timeline">
											<li>
												<div class="timeline-badge"><em class="fa fa-camera"></em></div>
												<div class="timeline-panel">
													<div class="timeline-heading">
														<h5 class="timeline-title mt-2">Feriado</h5>
													</div>
													<div class="timeline-body">
														<p>28 y 29 de julio feriado largo</p>
													</div>
												</div>
											</li>
											<li>
												<div class="timeline-badge primary"><em class="fa fa-link"></em></div>
												<div class="timeline-panel">
													<div class="timeline-heading">
														<h5 class="timeline-title mt-2">Comprar Suministros</h5>
													</div>
													<div class="timeline-body">
														<ol type="1">
														  <li>Guantes</li>
														  <li>Agujas</li>
														  <li>Limpiador</li>
														</ol>
													</div>
												</div>
											</li>
											<li>
												<div class="timeline-badge"><em class="fa fa-paperclip"></em></div>
												<div class="timeline-panel">
													<div class="timeline-heading">
														<h5 class="timeline-title mt-2">Recoger Resultados</h5>
													</div>
													<div class="timeline-body">
														<p>Paciente Magaly, recoger radiografia.</p>
													</div>
												</div>
											</li>
										</ul>
									</div>
								</div>
								<!--
								<div class="card mb-4">
									<div class="card-block">
										<h3 class="card-title">Todo List</h3>
										<div class="dropdown card-title-btn-container">
											<button class="btn btn-sm btn-subtle dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><em class="fa fa-cog"></em></button>
											<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"><a class="dropdown-item" href="#"><em class="fa fa-search mr-1"></em> More info</a>
												<a class="dropdown-item" href="#"><em class="fa fa-thumb-tack mr-1"></em> Pin Window</a>
												<a class="dropdown-item" href="#"><em class="fa fa-remove mr-1"></em> Close Window</a></div>
										</div>
										<h6 class="card-subtitle mb-2 text-muted">A simple checklist</h6>
										<ul class="todo-list mt-2 mb-2">
											
											<li class="todo-list-item">
												<div class="checkbox mt-1 mb-2">
													<div class="custom-control custom-checkbox">
														<input type="checkbox" class="custom-control-input" id="customCheck1">
														<label class="custom-control-label custom-control-description" for="customCheck1">Make Coffee</label>
													<div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
												</div>
											</li>
											<li class="todo-list-item">
												<div class="checkbox mt-1 mb-2">
													<div class="custom-control custom-checkbox">
														<input type="checkbox" class="custom-control-input" id="customCheck2">
														<label class="custom-control-label custom-control-description" for="customCheck2">Check emails</label>
													<div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
												</div>
											</li>
											<li class="todo-list-item">
												<div class="checkbox mt-1 mb-2">
													<div class="custom-control custom-checkbox">
														<input type="checkbox" class="custom-control-input" id="customCheck3">
														<label class="custom-control-label custom-control-description" for="customCheck3">Reply to Jane</label>
													<div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
												</div>
											</li>
											<li class="todo-list-item">
												<div class="checkbox mt-1 mb-2">
													<div class="custom-control custom-checkbox">
														<input type="checkbox" class="custom-control-input" id="customCheck4">
														<label class="custom-control-label custom-control-description" for="customCheck4">Work on the new design</label>
													<div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
												</div>
											</li>
											<li class="todo-list-item">
												<div class="checkbox mt-1 mb-2">
													<div class="custom-control custom-checkbox">
														<input type="checkbox" class="custom-control-input" id="customCheck5">
														<label class="custom-control-label custom-control-description" for="customCheck5">Get feedback</label>
													<div class="float-right action-buttons"><a href="#" class="trash"><em class="fa fa-trash"></em></a></div>
												</div>
											</li>
										</ul>
										<div class="card-footer todo-list-footer">
											<div class="input-group">
												<input id="btn-input" type="text" class="form-control input-md" placeholder="Add new task" /><span class="input-group-btn">
													<button class="btn btn-primary btn-md" id="btn-todo">Add</button>
											</span></div>
										</div>
									</div>
								</div>
								-->
								{% endblock %}
							</div>
						</section>
						<section class="row">
							<div class="col-12 mt-1 mb-4">Creado por <a href="https://www.medialoot.com">Joejhona</a></div>
						</section>
					</div>
				</section>
			</main>
		</div>
	</div>

	<div><a href="{% url 'sudentis:index' %}">Ir a Sudentis</a></div>
	
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script src="{% static 'js/chart-data.js' %}"></script>
    <script src="{% static 'js/easypiechart.js' %}"></script>
    <script src="{% static 'js/easypiechart-data.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script>
	    var startCharts = function () {
	                var chart1 = document.getElementById("line-chart").getContext("2d");
	                window.myLine = new Chart(chart1).Line(lineChartData, {
	                responsive: true,
	                scaleLineColor: "rgba(0,0,0,.2)",
	                scaleGridLineColor: "rgba(0,0,0,.05)",
	                scaleFontColor: "#c5c7cc "
	                });
	            }; 
	        window.setTimeout(startCharts(), 1000);
    </script>
    <script src="{% static 'js/tether.min.js' %}"></script>
</body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block navpills %}
{% if user.is_authenticated %}
    {% if user.dentist %}
        <li class="nav-item"><a class="nav-link" href="{% url 'sudentis:dentist-detail' user.dentist.pk %}"><em class="fa fa-calendar-o"></em> Ir a mi Cuenta de Dentist</a></li>
    {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'sudentis:dentist-create' %}"><em class="fa fa-calendar-o"></em> Registrate como Dentista</a></li>
    {% endif %}    
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Ir a mi Cuenta de Provider</a></li>
{% endif %}
<li class="nav-item"><a class="nav-link" href="{% url 'sudentis:index' %}"><em class="fa fa-calendar-o"></em> Sudentis 2.0 </a></li>
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Sudentis Provider 1.0 </a></li>
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Comentarios </a></li>
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Sugerencias </a></li>
{% endblock %}
{% block content %}
    <div class="card text-white bg-info">
        <div class="card-header"><h2 class="card-title">1. Registrate como Dentista o Provedor</h2></div>
        <div class="card-block">
            <form class="form" method="post">
                {% csrf_token %}
                {% load add_attr %}
                {% if form.errors %}
                <p>error del form</p>
                <p>{{ form.errors }}</p>
                {% endif %}
                {% for field in form %}
                <div class="form-group row">
                    <label class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                    <div class="col-md-9">
                        {{ field|add_attr:'class:form-control' }}
                        {% if field.help_text %}        
                            <small class="form-text text-white">{{ field.help_text|safe }}</small>
                        {% endif %}
                    </div>
                </div>                
                {% endfor %}
                <input class="btn btn-sm btn-primary font-weight-bold" type="submit" value="Proveedor o Dentista">
            </form>
        </div>
    </div>
{% endblock %}