jedentist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', views.homepage, name='index-app'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sudentis/', include('sudentis.urls')),
]

urlpatterns += staticfiles_urlpatterns()

sudentis/urls.py
from django.urls import path
from .views import index, DentistCreate, DentistDetailView, ClinicCreate, ClinicDetailView, HistoryUpdate, HistoryDetailView, dentist_add_work, attention_add, PatientUpdate, patient_add, PatientDetailView

app_name = 'sudentis'

urlpatterns = [
    path('', index, name='index'), # ex: /sudentis/
    path('dentist-create/', DentistCreate.as_view(), name='dentist-create'),
    path('dentist/<int:pk>/', DentistDetailView, name='dentist-detail'),
    path('clinic-create/', ClinicCreate.as_view(), name='clinic-create'),
    path('clinic/<int:pk>/', ClinicDetailView, name='clinic-detail'),
    path('clinic/<int:pk>/dentist-add/', dentist_add_work, name='dentist-add'),
    path('clinic/<int:pk>/patient-add/', patient_add, name='patient-add'),
    path('history-update/<int:pk>/', HistoryUpdate.as_view(), name='history-update'),
    path('history/<int:pk>/', HistoryDetailView, name='history-detail'),
    path('history/<int:pk>/attention-add/', attention_add, name='attention-add'),
    path('patient-update/<int:pk>/', PatientUpdate.as_view(), name='patient-update'),
    path('patient/<int:pk>/', PatientDetailView.as_view(), name='patient-detail')
]

sudentis/models.py
import datetime
from django.utils import timezone
from django.conf import settings
from django.db import models
from django.urls import reverse

class Dentist(models.Model):
    dentist_dni     = models.PositiveIntegerField('DNI:', primary_key=True)
    dentist_name    = models.CharField('Nombre y Apellido:',max_length=70)
    dentist_create  = models.DateTimeField(default=datetime.datetime.now)
    dentist_user    = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return 'Dentista: %s' % self.dentist_name 

    def get_absolute_url(self, **kwargs): 
        return reverse('sudentis:dentist-detail', kwargs={'pk': self.dentist_dni})

class Patient(models.Model):
    patient_dni         = models.PositiveIntegerField('DNI del paciente:', primary_key=True, help_text='Colocar el DNI')
    patient_name        = models.CharField('Nombres del paciente:',max_length=40)
    patient_age         = models.PositiveIntegerField('Edad del paciente:', default=18)
    #last_name   = models.CharField('Apellidos:',max_length=100)

    def __str__(self):
        return 'Paciente: %s' % (self.patient_name)

    def get_absolute_url(self, **kwargs): 
        #return reverse('sudentis:index')
        return reverse('sudentis:patient-detail', kwargs={'pk':self.patient_dni})

class Clinic(models.Model):
    clinic_name     = models.CharField('Nombre:', max_length=40, help_text='Si deseas no lo pongas')
    clinic_ruc      = models.PositiveIntegerField('RUC:', primary_key=True, help_text='Solo ingresa tu RUC y se extraeran los datos de la SUNAT para crear tu Clinica')
    clinic_user     = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    clinic_workers  = models.ManyToManyField(Dentist, default=None)
    clinic_patients = models.ManyToManyField(Patient, through='History', default=None)
    clinic_create   = models.DateTimeField(default=datetime.datetime.now)

    def get_absolute_url(self, **kwargs): 
        return reverse('sudentis:clinic-detail', kwargs={'pk': self.clinic_ruc})

class History(models.Model): 
    history_num         = models.AutoField(primary_key=True)
    history_patient     = models.ForeignKey(Patient, on_delete=models.CASCADE) 
    history_clinic      = models.ForeignKey(Clinic, on_delete=models.CASCADE) 
    history_treatment   = models.CharField('Tratamiento',max_length=500)

    def get_absolute_url(self, **kwargs): 
        return reverse('sudentis:history-detail', kwargs={'pk': self.pk})

class Attention(models.Model):
    attention_id        = models.AutoField(primary_key=True)
    attention_text      = models.CharField('Atencion:', max_length=500)
    attention_price     = models.PositiveIntegerField('Costo:')
    attention_create    = models.DateTimeField('Fecha de atencion:', default=datetime.datetime.now) 
    attention_history   = models.ForeignKey(History, on_delete=models.CASCADE) 

    def was_attend_recently(self): 
        return self.date_att >= timezone.now() - datetime.timedelta(days=1) 

sudentis/forms.py
from django import forms
from django.forms import ModelForm, Textarea 
from .models import Attention, History, Patient

class DentistIdForm(forms.Form):
    # Agregar el validador de max y minimo aunque no creo que sea necesario
    your_id_dentist = forms.CharField(label='Agregar Dentistas',help_text='Ingresa la Colegiatura')

class AttentionForm(ModelForm):
    class Meta:
        model   = Attention
        fields  = ['attention_text','attention_price']
        widgets = {'attention_text': Textarea(attrs={'cols': 80, 'rows': 5}),}

class PatientForm(ModelForm):
    class Meta:
        model  = Patient
        fields = ['patient_dni']
        labels = {'patient_dni':'Buscar o Crear Historia',}

class HistoryForm(ModelForm):
    class Meta:
        model  = History
        fields = ['history_num']

sudentis/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView
from .models import Dentist, Clinic, History, Attention, Patient
from .personalfunctions import add_perm_personal
from .forms import DentistIdForm, AttentionForm, HistoryForm, PatientForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate #, get_permission_codename 
from django.contrib.auth.models import Permission, User
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.detail import DetailView


def index(request):
    dentist_list = Dentist.objects.order_by('-dentist_create')[:5]
    context = {'dentist_list': dentist_list}
    usuario = request.user
    holas   = usuario.get_all_permissions()#agregar el object para ver si sale algo
    #holass = get_permission_codename()
    print(holas)
    #revisa la pagina 704
    return render(request, 'sudentis/index.html', context)

def dentist_add_work(request, pk):
    if request.method == 'POST':
        form_dent   = DentistIdForm(request.POST)
        if form_dent.is_valid():
            dentist = form_dent.cleaned_data['your_id_dentist']
            try:
                user_work   = User.objects.get(username=dentist)
            except User.DoesNotExist:
                return HttpResponseRedirect(reverse('sudentis:clinic-detail', kwargs={'pk': pk}))
            dentista = user_work.dentist
            if dentista:
                content_type     = ContentType.objects.get_for_model(Dentist)
                permission       = Permission.objects.get(
                    codename     = 'can_view_only_'+request.user.username,
                    content_type = content_type,
                )
                user_work.user_permissions.add(permission)
                clinica  = Clinic.objects.get(clinic_user=request.user)
                clinica.clinic_workers.add(dentista)
                #puede redirigir a un json formato o aun aviso
            return HttpResponseRedirect(reverse('sudentis:clinic-detail', kwargs={'pk': pk}))       

def attention_add(request, pk):
    if request.method == 'POST':
        form = AttentionForm(request.POST)
        new_attention = form.save(commit=False)
        historia = get_object_or_404(History, history_num=pk)
        new_attention.attention_history = historia
        new_attention.save()
        form.save_m2m()
        return HttpResponseRedirect(reverse('sudentis:history-detail', kwargs={'pk': pk}))
        #return reverse('sudentis:history-detail', kwargs={'pk': pk, 'dni': dni})

@login_required
def patient_add(request, pk):
    if request.method == 'POST':
        form_pati = PatientForm(request.POST)
        if form_pati.is_valid():
            patient_dni = form_pati.cleaned_data['patient_dni']
            patient_new, created_patient = Patient.objects.get_or_create(patient_dni=patient_dni)
            clinica = get_object_or_404(Clinic, pk=pk)
            history_new, created_history = History.objects.get_or_create(history_patient=patient_new, 
                                                history_clinic=clinica)
            #adicionar permisos para que pueda agregar historias o pacientes, revisar
            if created_patient is True:#--> se creo el paciente
                return HttpResponseRedirect(reverse('sudentis:patient-update', kwargs={'pk':patient_dni}))
            elif created_history is True:
                return HttpResponseRedirect(reverse('sudentis:history-update', kwargs={'pk':patient_dni}))
            else:
                return HttpResponseRedirect(reverse('sudentis:history-detail', kwargs={'pk':patient_dni}))


@method_decorator(login_required, name='dispatch')
class DentistCreate(CreateView):
    model = Dentist
    fields = ['dentist_name','dentist_dni']    
    def form_valid(self, form):
        form.instance.dentist_user = self.request.user
        add_perm_personal(self,Dentist,can_view=True,can_edit=True)
        return super().form_valid(form)

@login_required
def DentistDetailView(request, pk):
    usuario = request.user
    dentista= get_object_or_404(Dentist, pk=pk)
    if usuario.has_perm('sudentis.can_view_only_'+dentista.dentist_user.username):
        context = {'dentista':dentista}
        return render(request, 'sudentis/dentist_detail.html', context)
    else:
        return redirect('sudentis:index')

@method_decorator(login_required, name='dispatch')
class ClinicCreate(CreateView):
    model = Clinic
    fields = ['clinic_name','clinic_ruc']    
    def form_valid(self, form):
        form.instance.clinic_user = self.request.user
        add_perm_personal(self,Clinic,can_view=True,can_edit=True)
        return super().form_valid(form)

@login_required
def ClinicDetailView(request, pk):
    usuario   = request.user
    clinica   = get_object_or_404(Clinic, pk=pk)
    historias = History.objects.filter(history_clinic=clinica)
    form_dent = DentistIdForm()
    form_pati = PatientForm()
    if usuario.has_perm('sudentis.can_view_only_'+clinica.clinic_user.username):
        context = {'clinica':clinica,'form_dent':form_dent,'form_pati':form_pati,'historias':historias,}
        return render(request, 'sudentis/clinic_detail.html', context)
    else:
        return redirect('sudentis:index')

@login_required
def HistoryDetailView(request, pk):
    usuario    = request.user
    historia   = get_object_or_404(History, pk=pk)
    atenciones = Attention.objects.filter(attention_history=historia)
    form       = AttentionForm()
    if usuario.has_perm('sudentis.can_view_only_'+historia.history_clinic.clinic_user.username):
        context = {'historia':historia, 'form':form, 'atenciones':atenciones}
        return render(request, 'sudentis/history_detail.html', context)
    else:
        return redirect('sudentis:index')

"""
class HistoryDetailView(DetailView):
    model = History
"""
@method_decorator(login_required, name='dispatch')
class PatientUpdate(UpdateView):
    model  = Patient
    fields = ['patient_name','patient_age','patient_dni']
    template_name_suffix = '_update_form'
    def get_success_url(self):
        #agrgar el condicinal y redirigir a la historia creada 
        if self.request.user.clinic.clinic_user:
            historia   = get_object_or_404(History, history_patient=self.object, history_clinic=self.request.user.clinic)
        elif self.request.user.dentist.clinic.clinic_workers:
            historia   = get_object_or_404(History, history_patient=self.object, history_clinic=self.request.user.dentist.clinic)
        return reverse('sudentis:history-update', kwargs={'pk': historia.pk})

class PatientDetailView(DetailView):
    model = Patient

@method_decorator(login_required, name='dispatch')
class HistoryUpdate(UpdateView):
    model  = History
    fields = ['history_treatment']
    template_name_suffix = '_update_form'
    def form_valid(self, form):
        form.instance.history_clinic = self.request.user.clinic
        return super().form_valid(form)

sudentis/templates/sudentis/clinic_detail.html
{% extends 'base_layout.html' %}

{% block header %}<h1 class="float-left text-center text-md-left">{{ clinica.clinic_name }}</h1>
    {% if user.is_authenticated %}
        {% if user.clinic.clinic_user %}
            <h3 class="mb-1 text-primary">Administrador</h3>
        {% elif user.dentist.clinic_workers %}
            <h3 class="mb-1 text-success">Dentista</h3>
        {% endif %}
    {% endif %}
    <h4 class="mb-1">Sudentis 2.0</h4>
{% endblock %}

{% block navpills %}
<li class="nav-item card-block">
        <form action="{% url 'sudentis:dentist-add' clinica.clinic_ruc %}" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% for field in form_dent %}
            <h4 class="mb-1 text-white">{{ field.label_tag }}</h4>
            <div class="input-group"><span class="input-group-prepend">
                <button class="btn btn-success" type="submit" title=""><i class="fa fa-plus fa-2x"></i></button>
                {{ field|add_attr:'class:form-control' }}
            </span>
            <small class="form-text text-white">{{ field.help_text }}</small>
            </div>
            {% endfor %}
        </form>
</li>
<li class="nav-item card-block">
        <form action="{% url 'sudentis:patient-add' clinica.clinic_ruc %}" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% for field in form_pati %}
            <h4 class="mb-1 text-white">{{ field.label_tag }}</h4>
            <div class="input-group"><span class="input-group-prepend">
                <button class="btn btn-success" type="submit" title=""><i class="fa fa-plus fa-2x"></i></button>
                {{ field|add_attr:'class:form-control' }}
            </span>
            <small class="form-text text-white">{{ field.help_text }}</small>
            </div>
            {% endfor %}
        </form>
</li>
{% endblock %}

{% block content %}

    <div><h3>Estas son tus historias</h3></div>
    <div>
        {% for historia in historias %}
            <ul><a href="{% url 'sudentis:history-detail' clinica.clinic_ruc %}">{{ historia }}</a></ul>
        {% endfor %}
    </div>
{% endblock %}

sudentis/templates/sudentis/clinic_form.html
{% extends 'base_layout.html' %}

{% block navpills %}
{% endblock %}

{% block content %}
<div class="card text-white bg-success">
    <div class="card-header"><h2 class="card-title">Crea tu Clinica</h2></div>
    <div class="card-block">
        <form class="form" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% if form.errors %}
            <p>{{ form.errors }}</p>
            {% endif %}
            {% for field in form %}
            <div class="form-group row">
                <label class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                <div class="col-md-9">
                    {{ field|add_attr:'class:form-control' }}
                    {% if field.help_text %}        
                        <small class="form-text text-white">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            </div>                
            {% endfor %}
            <input class="btn btn-sm btn-primary font-weight-bold" type="submit" value="Crear mi Clinica">
            <input class="btn btn-sm btn-info font-weight-bold" type="submit" value="Crear y Editar mi Clinica">
        </form>
    </div>
</div>
{% endblock %}

{% block helpers %}
{% endblock %}

sudentis/templates/sudentis/dentist_detail.html
{% extends 'base_layout.html' %}

{% block header %}
    <h1 class="float-left text-center text-md-left">Sudentis 2.0</h1>
    <h3 class="mb-1 text-primary">Consultorio Personal</h3>    
{% endblock %}

{% block navpills %}
{% if user.is_authenticated %}
    {% if user.clinic.clinic_user %}
        <li class="nav-item"><a class="nav-link" href="{% url 'sudentis:clinic-detail' user.clinic.pk %}"><em class="fa fa-calendar-o"></em> Ir a mi Clinica {{ user.clinic.clinic_name }} </a></li>
    {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'sudentis:clinic-create' %}"><em class="fa fa-calendar-o"></em> Crear mi Consultorio </a></li>
    {% endif %}
    {% if user.dentist.clinic.clinic_workers %}
        {% for clinic in user.dentist.clinic.clinic_workers %}
            {{ clinic.clinic_name }}
            <li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Crear Historia</a></li>
        {% endfor %}
    {% endif %}
{% endif %}
{% endblock %}

{% block content %}
    <div><h2>Lista de Historias creadas</h2></div>
    <div><h1>Listado de Pacientes Atendidos</h1></div>
{% endblock %}

sudentis/templates/sudentis/dentist_form.html
{% extends 'base_layout.html' %}

{% block navpills %}
{% endblock %}

{% block content %}
<div class="card text-white bg-info">
    <div class="card-header"><h2 class="card-title">2. Termina de Registrarte</h2></div>
    <div class="card-block">
        <form class="form" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% if form.errors %}
            <p>error del form</p>
            <p>{{ form.errors }}</p>
            {% endif %}
            {% for field in form %}
            <div class="form-group row">
                <label class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                <div class="col-md-9">
                    {{ field|add_attr:'class:form-control' }}
                    {% if field.help_text %}        
                        <small class="form-text text-white">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            </div>                
            {% endfor %}
            <input class="btn btn-sm btn-primary font-weight-bold" type="submit" value="Proveedor o Dentista">
        </form>
    </div>
</div>
{% endblock %}

{% block helpers %}
{% endblock %}

sudentis/templates/sudentis/history_detail.html
{% extends 'base_layout.html' %}

{% block header %}
    {% if user.is_authenticated %}
        {% if user.clinic.clinic_user %}
            <h1 class="float-left text-center text-md-left">{{ user.clinic.clinic_name }}</h1>
            <h3 class="mb-1 text-primary">Administrador</h3>
        {% elif user.dentist.clinic_workers %}
            <h1 class="float-left text-center text-md-left">{{ user.dentist.clinic_workers.clinic_name }}</h1>
            <h3 class="mb-1 text-success">Dentista</h3>
        {% endif %}
    {% endif %}
    <h4 class="mb-1">Sudentis 2.0</h4>
{% endblock %}

{% block content %}
<div class="card bg-primary text-white">
    <div class="card-header"><h2 class="card-title">Historia N° {{ historia.pk }}</h2></div>
    <div class="card-block">
        <p>{{ historia.history_patient }}</p>
        <p>{{ historia.history_treatment }}</p>   
    </div>
</div>
<br>
<div class="card bg-success text-white">
    <div class="card-header"><h2 class="card-title">Crear Atencion</h2></div>
    <div class="card-block">
        <form action="{% url 'sudentis:attention-add' historia.pk %}" class="form" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% if form.errors %}
            <p>{{ form.errors }}</p>
            {% endif %}
            {% for field in form %}
            <div class="form-group row">
                <label class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                <div class="col-md-9">
                    {{ field|add_attr:'class:form-control' }}
                    {% if field.help_text %}        
                        <small class="form-text text-white">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            </div>                
            {% endfor %}
            <input class="btn btn-sm btn-info font-weight-bold" type="submit" value="Guardar Atención">
        </form>
    </div>
</div>
{% for atencion in atenciones %}
    <br>
    <div class="card bg-info text-white">
        <div class="card-header"><h2 class="card-title">Atencion {{ atencion.attention_create }}</h2></div>
        <div class="card-block">
            {{ atencion.attention_text }}
        </div>
    </div>
{% endfor %}
{% endblock %}

sudentis/templates/sudentis/history_form.html
{% extends 'base_layout.html' %}

{% block header %}
    {% if user.is_authenticated %}
        {% if user.clinic.clinic_user %}
            <h1 class="float-left text-center text-md-left">{{ user.clinic.clinic_name }}</h1>
            <h3 class="mb-1 text-primary">Administrador</h3>
        {% elif user.dentist.clinic_workers %}
            <h1 class="float-left text-center text-md-left">{{ user.dentist.clinic_workers.clinic_name }}</h1>
            <h3 class="mb-1 text-success">Dentista</h3>
        {% endif %}
    {% endif %}
    <h4 class="mb-1">Sudentis 2.0</h4>
{% endblock %}

{% block content %}

<div class="card bg-default">
    <div class="card-header"><h2 class="card-title">Creando Historia</h2></div>
     <div class="card-block">
        <form class="form" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% if form.errors %}
            <p>{{ form.errors }}</p>
            {% endif %}
            {% for field in form %}
            <div class="form-group row">
                <label class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                <div class="col-md-9">
                    {{ field|add_attr:'class:form-control' }}
                    {% if field.help_text %}        
                        <small class="form-text text-white">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            </div>                
            {% endfor %}
            <input class="btn btn-sm btn-primary font-weight-bold" type="submit" value="Guardar Historia">
        </form>
    </div>
</div>


{% endblock %}

sudentis/templates/sudentis/history_update_form.html
{% extends 'base_layout.html' %}

{% block header %}
    {% if user.is_authenticated %}
        {% if user.clinic.clinic_user %}
            <h1 class="float-left text-center text-md-left">{{ user.clinic.clinic_name }}</h1>
            <h3 class="mb-1 text-primary">Administrador</h3>
        {% elif user.dentist.clinic_workers %}
            <h1 class="float-left text-center text-md-left">{{ user.dentist.clinic_workers.clinic_name }}</h1>
            <h3 class="mb-1 text-success">Dentista</h3>
        {% endif %}
    {% endif %}
    <h4 class="mb-1">Sudentis 2.0</h4>
{% endblock %}

{% block content %}
<div class="card bg-light">
    <div class="card-header"><h2 class="card-title">Creando Historia N° {{ object.pk }}</h2></div>
    <div class="card-block">
        <form class="form" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% if form.errors %}
            <p>{{ form.errors }}</p>
            {% endif %}
            {% for field in form %}
            <div class="form-group row">
                <label class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                <div class="col-md-9">
                    {{ field|add_attr:'class:form-control' }}
                    {% if field.help_text %}        
                        <small class="form-text text-white">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            </div>                
            {% endfor %}
            <input class="btn btn-sm btn-primary font-weight-bold" type="submit" value="Guardar Historia">
        </form>
        <div class="card-footer">
            <h3>Nombre: {{ object.history_patient.patient_name }}</h3>
            <h3>DNI: {{ object.history_patient.patient_dni }}</h3>
            <h3>Edad: {{ object.history_patient.patient_age }}</h3>
        </div>
    </div>
</div>
{% endblock %}

sudentis/templates/sudentis/index.html
{% extends 'base_layout.html' %}

{% block navpills %}
{% if user.is_authenticated %}
    {% if user.clinic.clinic_user %}
        <li class="nav-item"><a class="nav-link" href="{% url 'sudentis:clinic-detail' user.clinic.pk %}"><em class="fa fa-calendar-o"></em> Ir a mi Clinica</a></li>
    {% endif %}
<li class="nav-item"><a class="nav-link" href="{% url 'sudentis:dentist-detail' user.dentist.pk %}"><em class="fa fa-calendar-o"></em> Ir a mi Consultorio </a></li>
{% else %}
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Conoce SUDENTIS 2.0 </a></li>
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Sudentis Clinic </a></li>
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Sudentis Home </a></li>
<li class="nav-item"><a class="nav-link" href="widgets.html"><em class="fa fa-calendar-o"></em> Sudentis Provider </a></li>
{% endif %}
{% endblock %}
{% block header %}Sudentis 2.0{% endblock %}
{% block content %}
    <h1>Dentistas Inscritos</h1>
    {% for dentist in dentist_list %}
        <h3>Usuario: {{ dentist.dentist_user.username }}</h3>
        <h3>Dentista: {{ dentist.dentist_name }}</h3>
        <h3>Dni: {{ dentist.dentist_dni }}</h3>
        <h3><a href="{% url 'sudentis:dentist-detail' dentist.dentist_dni %}">Ve a la pagina de {{ dentist.dentist_user.username }}</a></h3>
    {% endfor %}
    <h1>Clinicas Inscritas</h1>
    <h1>Pecientes Atendidos</h1>
{% endblock %}

sudentis/templates/sudentis/patient_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <p>Reporter: {{ object.patient_dni }}</p>
    <p>Published: {{ object.patient_name }}</p>
    <p>Date: {{ object.patient_age }}</p>

    {% if user.is_authenticated %}
        {{ user.username }}
        {{ user.dentist.clinic_workers }}
    {% endif %}


{% endblock %}

sudentis/templates/sudentis/patient_update_form.html
{% extends 'base_layout.html' %}

{% block header %}
    {% if user.is_authenticated %}
        {% if user.clinic.clinic_user %}
            <h1 class="float-left text-center text-md-left">{{ user.clinic.clinic_name }}</h1>
            <h3 class="mb-1 text-primary">Administrador</h3>
        {% elif user.dentist.clinic_workers %}
            <h1 class="float-left text-center text-md-left">{{ user.dentist.clinic_workers.clinic_name }}</h1>
            <h3 class="mb-1 text-success">Dentista</h3>
        {% endif %}
    {% endif %}
    <h4 class="mb-1">Sudentis 2.0</h4>
{% endblock %}

{% block content %}
<div class="card bg-default">
    <div class="card-header"><h2 class="card-title">Datos del Paciente</h2></div>
    <div class="card-block">
        <form class="form" method="post">
            {% csrf_token %}
            {% load add_attr %}
            {% if form.errors %}
            <p>{{ form.errors }}</p>
            {% endif %}
            {% for field in form %}
            <div class="form-group row">
                <label class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                <div class="col-md-9">
                    {{ field|add_attr:'class:form-control' }}
                    {% if field.help_text %}        
                        <small class="form-text text-white">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            </div>                
            {% endfor %}
            <input class="btn btn-sm btn-primary font-weight-bold" type="submit" value="Guardar Historia">
        </form>
    </div>
</div>

{% endblock %}